### ISSUE TITLE
trouble reading SNV vcf

### ISSUE THREAD

**Issue by srinipr4** [hartwigmedical/gridss-purple-linx#27]
Hi, I am having trouble using the strelka VCF file in the gridss-linx-purple pipeline. It runs successfully through GRIDSS, AMBER, COBALT and seems to get stuck in the PURPLE run when it reaches the step that uses the vcf file.  I have added an "AD" field in the vcf as well since strelka doesn't report it. The naming convention for the sample if the provided sample name"_T" as required. 
e.g.
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE_T
1	10404	.	C	G	.	LowEVS	DP=797;MQ=16.15;MQ0=444;NT=ref;QSS=34;QSS_NT=34;ReadPosRankSum=0.69;SGT=CC->CG;SNVSB=0;SOMATIC;SomaticEVS=0.72;TQSS=2;TQSS_NT=2	DP:FDP:
SDP:SUBDP:AU:CU:GU:TU:AD	54:10:0:0:0,1:43,348:1,5:0,0:43,1

I get this error which I am not able to understand. Could you please help me resolve this? Thank you!!

Exception in thread "main" java.lang.NullPointerException
	at com.hartwig.hmftools.common.variant.AllelicDepth.containsAllelicDepth(AllelicDepth.java:20)
	at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:126)
	at com.hartwig.hmftools.common.variant.SomaticVariantFactory.createVariant(SomaticVariantFactory.java:118)
	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.lambda$somaticVariants$0(PurityPloidyEstimateApplication.java:391)
	at com.hartwig.hmftools.common.variant.enrich.VariantHotspotEnrichment.accept(VariantHotspotEnrichment.java:38)
	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.somaticVariants(PurityPloidyEstimateApplication.java:399)
	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.<init>(PurityPloidyEstimateApplication.java:149)
	at com.hartwig.hmftools.purple.PurityPloidyEstimateApplication.main(PurityPloidyEstimateApplication.java:103)

**Comment by srinipr4** [comment]
I figured out the problem - The header had to be SAMPLET not SAMPLE_T.
Closing the ticket. Sorry for the trouble!
