### ISSUE TITLE
GRIPSS memory issue

### ISSUE THREAD

**Issue by Scottdson** [hartwigmedical/gridss-purple-linx#35]
We're getting a Java hap space error from GRIPSS while using the GRIDSS-PURPLE-LINX docker.

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.lang.String.substring(String.java:1969)
        at htsjdk.tribble.util.ParsingUtils.split(ParsingUtils.java:204)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseInfo(AbstractVCFCodec.java:517)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:428)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:384)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:328)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:48)
        at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:173)
        at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:205)
        at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:149)
        at com.hartwig.hmftools.gripss.GripssApplication.hardFilterAndRealign(GripssApplication.kt:166)
        at com.hartwig.hmftools.gripss.GripssApplication.run(GripssApplication.kt:94)
        at com.hartwig.hmftools.gripss.GripssApplicationKt.main(GripssApplication.kt:42)`

From the gridss-purple-linx.sh script it looks like the heap size is hard coded.  Can this be altered to allow users to increase this size?

Thanks

**Comment by p-priestley** [comment]
We won't fix this, but GRIPSS is currently being rewritten to deal with the memory issue.    Please follow this issue for any updates

https://github.com/hartwigmedical/hmftools/issues/210
